services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PEER_ID=peer1
      - PORT=8080
    volumes:
      - peer1_data:/app/out

  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PEER_ID=peer2
      - PORT=8080
    volumes:
      - peer2_data:/app/out

  peer3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PEER_ID=peer3
      - PORT=8080
    volumes:
      - peer3_data:/app/out

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - peer1
      - peer2
      - peer3
    volumes:
      - ./test_data:/test_data

volumes:
  peer1_data:
  peer2_data:
  peer3_data:
