services:
  peer1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PEER_ID=peer1
      - PORT=8080
    volumes:
      - peer1_data:/app/out
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  peer2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PEER_ID=peer2
      - PORT=8080
    volumes:
      - peer2_data:/app/out
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  peer3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PEER_ID=peer3
      - PORT=8080
    volumes:
      - peer3_data:/app/out
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  peer1_data:
  peer2_data:
  peer3_data:
